### ISSUE TITLE
RSS is broken

### ISSUE THREAD

**Issue by iamihalcea** [therandomsecurityguy/randomsec-blog#1]
Hi! I'd like to keep up to date with your blog and was hoping to use RSS for it, but it seems broken. I didn't have much of a look into what the problem might be, just wanted to give a shout out about it :)

**Comment by therandomsecurityguy** [comment]
Thanks for the heads up, @iamihalcea! I moved the RSS link to the [posts](https://therandomsecurityguy.com/posts/index.xml) feed.

**Comment by iamihalcea** [comment]
Perfect, thank you!
